version: '1.0'
services:
  web:
    build: .
    env_file:
      - .env
    volumes:
      - .:/app
  redis:
    image: bitnami/redis:7.0
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      - '6379:6379'
    volumes:
      - redis-db:/val/lib/redis/data
  clickhouse:
    image: bitnami/clickhouse:latest
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - clickhouse-db:/val/lib/clickhouse/data
  postgre:
    image: postgres:alpine
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_HOST=${DB_HOST}
    ports:
      - "5432:5432"
    volumes:
      - postgre-db:/val/lib/postgresql/data1
  kafka:
    image: 'bitnami/kafka:latest'
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes
volumes:
  redis-db:
  clickhouse-db:
  postgre-db: